import React, { useState } from 'react';
import { SustainabilityMetrics } from '../../types';
import {
  Leaf,
  ShieldCheck,
  Award,
  CheckCircle2,
  X,
  Printer,
  QrCode,
  Lock,
  Sparkles,
  TreePine,
  Zap,
  Fuel,
} from 'lucide-react';

interface SustainabilityCertificateModalProps {
  isOpen: boolean;
  onClose: () => void;
  metrics: SustainabilityMetrics;
  corridorFilter: string;
}

export const SustainabilityCertificateModal: React.FC<SustainabilityCertificateModalProps> = ({
  isOpen,
  onClose,
  metrics,
  corridorFilter,
}) => {
  const [downloaded, setDownloaded] = useState(false);

  if (!isOpen) return null;

  const certificateNumber = `IR-ESG-${new Date().getFullYear()}-${Math.floor(100000 + Math.random() * 900000)}`;
  const certDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  const handlePrintOrDownload = () => {
    setDownloaded(true);
    window.print();
    setTimeout(() => setDownloaded(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-[#0b171c] border border-emerald-500/50 rounded-2xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl relative overflow-hidden flex flex-col gap-6 text-slate-200 font-mono">
        {/* Background Watermark */}
        <div className="absolute right-[-60px] bottom-[-60px] opacity-5 pointer-events-none text-emerald-400">
          <Leaf className="w-96 h-96" />
        </div>

        {/* Certificate Header */}
        <div className="flex items-start justify-between border-b border-emerald-900/60 pb-4 relative z-10">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-emerald-950/90 border border-emerald-400/60 flex items-center justify-center text-emerald-400 shadow-md shadow-emerald-950/80">
              <Award className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-bold text-white tracking-wide">
                  INDIAN RAILWAYS ESG DECARBONIZATION CERTIFICATE
                </h3>
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                  FORM GR-ESG-701
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Verified under ISO 14064-1 GHG Protocol & RDSO Green Freight Initiative
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Certificate Body */}
        <div className="bg-[#061014] p-5 sm:p-6 rounded-xl border border-emerald-900/40 space-y-4 text-xs relative z-10">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
            <div>
              <span className="text-slate-400 block text-[11px]">Accreditation ID:</span>
              <span className="text-emerald-400 font-bold text-sm tracking-wider">{certificateNumber}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[11px]">Audit Timestamp:</span>
              <span className="text-white font-bold">{certDate} (Real-time Live Sync)</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[11px]">Evaluation Scope:</span>
              <span className="text-cyan-300 font-bold">
                {corridorFilter === 'ALL' ? 'Multi-Corridor National Grid' : corridorFilter}
              </span>
            </div>
          </div>

          <div className="space-y-3 pt-1">
            <p className="text-slate-300 leading-relaxed text-[11px]">
              This certifies that the railway maintenance block schedule generated by{' '}
              <strong className="text-emerald-300">RAILSYNC AI Engine</strong> has successfully
              suppressed non-productive locomotive engine idling and minimized pre-block signal dwell times
              in compliance with RDSO Net-Zero Traction Directives.
            </p>

            {/* Empirical Savings Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
              <div className="p-2.5 rounded-lg bg-emerald-950/40 border border-emerald-700/40">
                <span className="text-[10px] text-slate-400 block">Total Carbon Abated</span>
                <span className="text-base font-black text-emerald-300 font-mono">
                  {metrics.totalCo2AbatedTonnes} MT CO₂e
                </span>
              </div>
              <div className="p-2.5 rounded-lg bg-amber-950/30 border border-amber-700/40">
                <span className="text-[10px] text-slate-400 block">Diesel Conserved</span>
                <span className="text-base font-black text-amber-300 font-mono">
                  {metrics.dieselSavedLiters.toLocaleString()} L
                </span>
              </div>
              <div className="p-2.5 rounded-lg bg-cyan-950/30 border border-cyan-700/40">
                <span className="text-[10px] text-slate-400 block">Auxiliary Grid Power</span>
                <span className="text-base font-black text-cyan-300 font-mono">
                  {metrics.electricSavedKwh.toLocaleString()} kWh
                </span>
              </div>
              <div className="p-2.5 rounded-lg bg-teal-950/30 border border-teal-700/40">
                <span className="text-[10px] text-slate-400 block">Tree Equivalent</span>
                <span className="text-base font-black text-teal-300 font-mono">
                  {metrics.treesOffsetEquivalent.toLocaleString()} Trees
                </span>
              </div>
            </div>
          </div>

          {/* Cryptographic Hash & Validation Stamp */}
          <div className="p-3 bg-slate-900/90 rounded-lg border border-emerald-900/50 flex items-center justify-between gap-3 mt-3">
            <div className="space-y-0.5">
              <span className="text-[10px] text-slate-400 block uppercase tracking-wider flex items-center gap-1">
                <Lock className="w-3 h-3 text-emerald-400" />
                Cryptographic ESG Verification Hash
              </span>
              <span className="text-emerald-300 font-mono text-[10px] sm:text-[11px] font-bold break-all">
                SHA-256: 9bfa482d83c27e9014dfa09028be5cf3486127419efb0113c054e8
              </span>
            </div>
            <div className="p-1.5 bg-white rounded border border-slate-300 shadow-sm shrink-0">
              <QrCode className="w-7 h-7 text-slate-950" />
            </div>
          </div>

          {/* Verification Statement */}
          <div className="p-3 bg-emerald-950/40 rounded-lg border border-emerald-500/40 flex items-center gap-2.5 text-emerald-200">
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
            <p className="text-[11px] leading-relaxed">
              <strong>Approved for Commercial Carbon Credit Ingestion:</strong> Estimated verified carbon abatement complies with Ministry of Railways Carbon Offset Framework (2025–2030).
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-between gap-3 relative z-10">
          <button
            onClick={handlePrintOrDownload}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs flex items-center gap-1.5 transition-colors border border-slate-700"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save PDF</span>
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2 rounded-lg bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 text-slate-950 font-bold text-xs flex items-center gap-2 shadow-lg shadow-emerald-950/60 transition-all"
          >
            <CheckCircle2 className="w-4 h-4" />
            <span>Dismiss Certificate</span>
          </button>
        </div>
      </div>
    </div>
  );
};
